# Dockerfile
# $ docker build -f Dockerfile.dev -t todo-frontend-dev
# $ docker run -p 3001:3001 -v "$(pwd):/usr/src/app/" todo-frontend-dev
# $ docker exec -it <CONTAINER ID> bash
# http://app:3001/

FROM node:16

WORKDIR /usr/src/app

COPY ./package.json .

COPY ./package-lock.json .

COPY . .

RUN npm config set package-lock false

# RUN npm install -g npm

RUN npm install

COPY . ./

RUN npm run build

RUN ls -l /usr/src/app

ENV REACT_APP_BACKEND_URL=http://localhost:3000/

# ENV PORT=3001

# EXPOSE 3001

CMD ["npm", "start"]