# docker-compose.dev.yml
# $ npm install
# $ docker-compose -f docker-compose.dev.yml down --volumes
# $ docker-compose -f docker-compose.dev.yml up --build
# http://localhost:3001/

version: '3.8'

services:
  app:
    image: todo-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001
    expose:
      - "3001"
    environment:
      - PORT=3001
    container_name: todo-frontend-dev