# docker-compose.dev.yml
# $ docker-compose -f docker-compose.dev.yml down --volumes
# $ docker-compose -f docker-compose.dev.yml up
# $ docker network create local_docker_network --subnet 10.0.1.0/24
# $ npm install nodemon --save-dev
# $ npm install express --save
# $ npm install
# $ MONGO_URL=mongodb://the_username:the_password@localhost:3456/the_database npm run dev
# $ docker exec -it <CONTAINER ID> bash
# http://localhost:3000/todos

version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
volumes:
  mongo_data: {}
